### ISSUE TITLE
Can javascript is includable?

### ISSUE THREAD

**Issue by dotku** [chris-l/html-include#3]
If te HTML part contains javascript how the page works?!

**Comment by chris-l** [comment]
Well, it didn't worked.

Since it uses `outerHTML`, any `<script>` tag inserted that way is not evaluated by the JavaScript engine.

However, after noticing that and googling about it, I read that jquery uses `eval` to execute the `<script>` tags included. So in the ed9df0e8d65445844fba9de1eba636429b20c7a commit, now I use `eval` to execute the content of the `<script>` tags.

I haven't done any heavy tests on it, but so far it seems to be working correctly; try it now!
