### ISSUE TITLE
Relative URLs in included document

### ISSUE THREAD

**Issue by trans** [chris-l/html-include#4]
I was playing around with w3c's [include-html](http://www.w3schools.com/howto/howto_html_include.asp) experimental tag. Problem I have with it is that relative links within the included document become relative to the parent document, not the child.

Does your `html-include` do the same?

**Comment by chris-l** [comment]
Well, first at all, you should know that is **not an w3c's specification**.

w3schools **is not** related to the W3C (w3schools even mentions  that on their [about page](http://www.w3schools.com/about/)).
By the way, the W3C actually had an [official teaching platform](http://www.webplatform.org/), that unfortunately, was discontinued. The best thing we have now is MDN.

Well, putting that aside. 

I haven't tested myself, but the answer I'm pretty sure is **yes**.
The reason is that what this element does is to insert the _raw content_ of the child HTML inside the parent HTML. It does not change anything at all of the included HTML.

Contrary to an iframe, that has it's own dom environment and url (among other things), here the included content is _only injected_ to the main html, and for that reason, have the same url. Therefore, any relative link should be relative to the current url. (the one you can see on your browser location bar)

So is not a problem, is the expected behavior.
